# Generated by Django 5.0.4 on 2024-04-15 16:13

import v1.models.server
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=255, null=True)),
                (
                    "url",
                    models.CharField(
                        max_length=255,
                        validators=[v1.models.server.OptionalSchemeURLValidator()],
                    ),
                ),
                ("max_level", models.IntegerField(editable=False, null=True)),
                ("settings", models.JSONField(editable=False, null=True)),
                ("customizations", models.JSONField(editable=False, null=True)),
                ("login_limit", models.IntegerField(editable=False, null=True)),
                ("active_sessions", models.IntegerField(editable=False, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("inactivity_counter", models.IntegerField(editable=False, null=True)),
            ],
        ),
    ]
