# Generated by Django 5.0.4 on 2024-04-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_server_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='inactivity_counter',
        ),
        migrations.AddField(
            model_name='server',
            name='up',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
