# Generated by Django 5.0.4 on 2024-05-02 22:25

import v1.models.server
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_server_inactivity_counter_server_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='id',
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[v1.models.server.OptionalSchemeURLValidator()]),
        ),
    ]
