# Generated by Django 5.0.4 on 2024-05-02 23:51

import v1.models.server
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_remove_server_id_alter_server_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(error_messages={'unique': 'A server with this URL already exists.'}, max_length=255, primary_key=True, serialize=False, validators=[v1.models.server.OptionalSchemeURLValidator()]),
        ),
    ]
