# Generated by Django 5.0.5 on 2024-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_server_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='customizations',
            new_name='settings_summary',
        ),
        migrations.AddField(
            model_name='server',
            name='expansions',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
