services:
    api:
        build: .
        command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
        restart: always
        volumes:
            - .:/app
            - static:/app/static
        expose:
            - 8000
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A api worker -l info
        restart: always
        volumes:
            - .:/app
        depends_on:
            - redis
    celery-beat:
        build: .
        command: celery -A api beat -l info
        restart: always
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis:alpine
        restart: always
    nginx:
        image: nginx
        ports:
            - 9969:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static:/app/static
        depends_on:
            - api
volumes:
    static:
